# Generated by Django 6.0.3 on 2026-08-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_entries", "0002_alter_dailyentry_operator"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyentry",
            name="technician_ack",
            field=models.BooleanField(default=False),
        ),
    ]
