# Generated by Django 6.0.3 on 2026-08-15 10:21

from django.db import migrations


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# daily_entries.migrations.0004_seed_user_roles

class Migration(migrations.Migration):

    replaces = [('daily_entries', '0004_seed_user_roles'), ('daily_entries', '0005_seed_user_roles')]

    dependencies = [
        ('daily_entries', '0003_dailyentry_technician_ack'),
    ]

    operations = [
        migrations.RunPython(
            code=daily_entries.migrations.0004_seed_user_roles.create_groups,
            reverse_code=daily_entries.migrations.0004_seed_user_roles.remove_groups,
        ),
    ]
