# Generated by Django 6.0.3 on 2026-08-15 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_entries", "0004_seed_user_roles"),
    ]

    operations = []
