# Generated by Django 6.0.3 on 2026-08-19 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_entries", "0005_seed_user_roles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyentry",
            name="operator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oxygen_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
