# Generated by Django 6.0.3 on 2026-09-11 21:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_entries", "0007_auto_20260819_0439"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyentry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
