# Generated by Django 6.0.3 on 2026-09-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_entries", "0008_dailyentry_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyentry",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="dailyentry",
            name="time",
            field=models.TimeField(),
        ),
    ]
