# Generated by Django 6.0.3 on 2026-09-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_entries", "0010_technician_dailyentry_technician"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyentry",
            name="technician",
        ),
    ]
