# Generated by Django 6.0.3 on 2026-06-20 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("oxygen_purity", models.DecimalField(decimal_places=2, max_digits=5)),
                ("pressure", models.DecimalField(decimal_places=2, max_digits=6)),
                ("flow_rate", models.DecimalField(decimal_places=2, max_digits=6)),
                ("pdp", models.DecimalField(decimal_places=2, max_digits=5)),
                ("notes", models.TextField(blank=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
