# Generated by Django 6.0.3 on 2026-07-15 02:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weekly_records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyentry",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
